[greeter]
background=/usr/share/backgrounds/aetheros/aetheros-greeter.png
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=DejaVu Sans 11
indicators=~host;~spacer;~clock;~spacer;~layout;~session;~power
clock-format=%H:%M
default-user-image=/usr/share/icons/aetheros/aetheros-avatar.png
