---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/initramfs-linux-fallback.img"
timeout: "5"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
efiDirectory: "/boot/efi"
distributor: "AetherOS"
