---
region: "Europe"
zone: "London"

localeGenPath: /etc/locale.gen

localeGen:
    - "en_US.UTF-8 UTF-8"
    - "ru_RU.UTF-8 UTF-8"

geoip:
    style: "json"
    url: "https://ipapi.co/json"
    selector: "country_code"
