---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 300MiB
efiSystemPartitionName: "AETHEROS_EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - reasonable

defaultFileSystemType: "ext4"

availableFileSystemTypes: [ "ext4", "btrfs", "xfs" ]

partitionLayout:
    -   name: "root"
        filesystem: "unknown"
        mountPoint: "/"
        size: 100%

drawNestedPartitions: true
alwaysShowPartitionLabels: true
allowManualPartitioning: true
