---
defaultGroups:
    - wheel
    - audio
    - video
    - storage
    - optical
    - network
    - power

autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    wheel
setRootPassword: true
doReusePassword: false

passwordRequirements:
    minLength: 4

allowWeakPasswords: true
allowWeakPasswordsDefault: false

hostname:
    location: EtcHostname
    writeHostsFile: true

userShell: "/bin/bash"
