---
showSupportUrl:         true
showKnownIssuesUrl:      false
showReleaseNotesUrl:     true
showDonateUrl:           false

requirements:
    requiredStorage:     10
    requiredRam:         2
    internetCheckUrl:    "https://archlinux.org"
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
