# AetherOS — Aether Installer (Calamares) sequence definition
---
modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs.conf
- id:       remove-live-user
  module:   shellprocess
  config:   remove-live-user.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - remove-live-user
  - umount
- show:
  - finished

branding: aetheros
prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
